# 自作関数の使用例

In [1]:
import sys
from pathlib import Path

# projectルートを追加
sys.path.append(str(Path().resolve().parent))

In [2]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

print("numpy:",np.__version__)
print("pandas:",pd.__version__)
print("matplotlib:",matplotlib.__version__)

numpy: 2.4.2
pandas: 3.0.1
matplotlib: 3.10.8

In [3]:
from src.data_loader import load_csv_with_datetime_index

df = load_csv_with_datetime_index(
    "../data/raw/M.csv",
    date_col="Year",
    date_format="%Y",
)

df.head()

=== CSV loaded ===
shape: (99, 7)
columns: ['Year', 'SG', 'D_SG', 'IG', 'D_IG', 'ALL', 'D_ALL']
=== DatetimeIndex set ===
<class 'pandas.DatetimeIndex'>
DatetimeIndex(['1920-01-01', '1921-01-01', '1922-01-01', '1923-01-01',
               '1924-01-01'],
              dtype='datetime64[us]', name='Year', freq=None)

              SG  D_SG    IG  D_IG   ALL  D_ALL
Year
1920-01-01   831    25  1843     8  2674     33
1921-01-01  1163    25  1833     7  2996     32
1922-01-01  1305    23  1972    10  3277     33
1923-01-01  1290    22  2068     5  3358     27
1924-01-01  1297    37  2175     3  3472     40

In [4]:
from src.preprocessing import normalize_default_counts

df = normalize_default_counts(df, scale=3000)
df.head()

[normalize_default_counts] created 'SG_norm' from 'D_SG' / 'SG' * 3000
[normalize_default_counts] created 'IG_norm' from 'D_IG' / 'IG' * 3000
[normalize_default_counts] created 'ALL_norm' from 'D_ALL' / 'ALL' * 3000

,SG,D_SG,IG,D_IG,ALL,D_ALL,SG_norm,IG_norm,ALL_norm
Year,,,,,,,,,
1920-01-01,831,25,1843,8,2674,33,90.252708,13.022246,37.023186
1921-01-01,1163,25,1833,7,2996,32,64.488392,11.456628,32.042724
1922-01-01,1305,23,1972,10,3277,33,52.873563,15.212982,30.210558
1923-01-01,1290,22,2068,5,3358,27,51.162791,7.253385,24.121501
1924-01-01,1297,37,2175,3,3472,40,85.582113,4.137931,34.562212

In [5]:
from src.init_params import build_init_params, init_params_to_series

x = df["ALL_norm"].to_numpy(dtype=float)

init_params = build_init_params(x, max_lag=20)

df_init_one = init_params_to_series(init_params, name="ALL")
display(df_init_one)

group                 ALL
lambda0_init    15.371267
alpha_init       1.608366
theta_init       0.871265
gamma_init       0.553767
lambda0_se       0.478434
alpha_se         0.031045
theta_se         0.008452
gamma_se         0.041713
lambda0_var      0.228899
alpha_var        0.000964
theta_var        0.000071
gamma_var         0.00174
dtype: object